### PR TITLE
Border properties

### PR DESCRIPTION
**Pull request by EliotRagueneau**
Associated issues: 

- #3199 

- This PR adds the following properties
 * **`border-cap`** : The cap style of the node's border; may be `butt`, `round` or `square`.
 * **`border-dash-pattern`** : The `dashed` line pattern which specifies alternating lengths of lines and gaps. (e.g. `[6, 3]`).
 * **`border-dash-offset`** : The `dashed` line offset (e.g. `24`). It is useful for creating edge animations.
 

**Checklist**

Author:

- [x] The proper base branch has been selected.  New features go on `unstable`.  Bug-fix patches can go on either `unstable` or `master`.
- [x] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.  Check this box if tests are not pragmatically possible (e.g. rendering features could include screenshots or videos instead of automated tests).
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (above).

Reviewers:

- [x] All automated checks are passing (green check next to latest commit).
- [x] At least one reviewer has signed off on the pull request.
- [x] For bug fixes:  Just after this pull request is merged, it should be applied to both the `master` branch and the `unstable` branch.  Normally, this just requires cherry-picking the corresponding merge commit from `master` to `unstable` -- or vice versa.

### CODE REVIEW

**Comment by EliotRagueneau** [comment]
I've started to implement `border-position` using the strategy defined at https://stackoverflow.com/a/34234589/11028828

However, I didn't want to create a new canvas for each nodes with this type of border for performance reason, and as the  author explained in the previous ticket, just by using it within the global context does create a lot of issues with the rest of rendering, so I've put on hold those changes for now, as you suggested @maxkfranz 

Let me know if you are aware of an easy way and performat way to do this. (inside can be done using clips also I beileve, but not outside)

**Comment by maxkfranz** [comment]
> I've started to implement `border-position` using the strategy defined at https://stackoverflow.com/a/34234589/11028828
> 
> However, I didn't want to create a new canvas for each nodes with this type of border for performance reason, and as the author explained in the previous ticket, just by using it within the global context does create a lot of issues with the rest of rendering, so I've put on hold those changes for now, as you suggested @maxkfranz

Yes, I wouldn't use GCO for this.

> 
> Let me know if you are aware of an easy way and performat way to do this. (inside can be done using clips also I beileve, but not outside)

Inside -- regular clip of node shape

Outside -- possibly an even-odd clip, with one box for the full bounds and the node shape or some other combination

See https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clip

**Comment by EliotRagueneau** [comment]
Just added the support to `border-position` as you suggested using clips and evenodd, thanks for the advice!

**Comment by EliotRagueneau** [comment]
This strategy might create issues if users are using a custome polygon which cross itself, like an hourglass for instance

**Comment by EliotRagueneau** [comment]
I've tested a custom hourglass shape and it still works great 🥳 
While doing so, I've realised that we didn't have any lineJoin property, and it becomes useful with outer border in my opinion, so I have added it

**Comment by EliotRagueneau** [comment]
Sorry about those missing semi colons

**Review by maxkfranz — APPROVED** [review]
@EliotRagueneau, anything else before this is merged in?

**Comment by EliotRagueneau** [comment]
No I think we're good on this one

**Pull request merged**
