### PR TITLE
Fix breadthfirst layout to center all rows vertically and each row horizontally and to respect a given bounding box

### PR DESCRIPTION
**Pull request by soetji**
Associated issues: 

- #3288 
- #3289 
- #3290 

**Notes

- This PR fixes all the issues above from:
Screenshot 2024-11-06 at 10 06 56 PM
Screenshot 2024-11-06 at 10 06 56 PM copy 2

https://github.com/user-attachments/assets/60891331-e04f-4d62-8d8a-40264131c404

- This PR fixes all the issues above to:

https://github.com/user-attachments/assets/cd39db4d-6365-411d-9798-a42cc9e48d23

- This PR updates `let` variable declarations to `const`, when appropriate,  in `src/extensions/layout/breadthfirst.js`

**Checklist**

Author:

- [ ] The proper base branch has been selected.  New features go on `unstable`.  Bug-fix patches can go on either `unstable` or `master`.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.  Check this box if tests are not pragmatically possible (e.g. rendering features could include screenshots or videos instead of automated tests).
- [ ] The associated GitHub issues are included (above).
- [ ] Notes have been included (above).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.
- [ ] For bug fixes:  Just after this pull request is merged, it should be applied to both the `master` branch and the `unstable` branch.  Normally, this just requires cherry-picking the corresponding merge commit from `master` to `unstable` -- or vice versa.

### CODE REVIEW

**Comment by mikekucera** [comment]
Hi. Thanks for the contribution, it looks good! 
Can you please retarget the pull request to the 'unstable' branch. Thanks.

**Comment by soetji** [comment]
> Hi. Thanks for the contribution, it looks good! Can you please retarget the pull request to the 'unstable' branch. Thanks.

Done

**Comment by soetji** [comment]
Replacing this PR with PR #3292 that is based on the unstable branch. It contains my commits only.

**Comment by soetji** [comment]
Closing

**Pull request closed without merging**
