### PR TITLE
Added `warnings` to initialisation options

### LINKED ISSUE #2258: Suppressing warning messages
**Issue type**
Core Library & Cose Layout.

Bug report

**Environment info**

- Cytoscape.js: v3.3.1:
- Browser: Chrome 71.0.3578.98 (Official Build) (64-bit):

**Current (buggy) behaviour**

I think this has to do with both the 'cose' layout as well as the core library. The main concern is adding nodes dynamically (using `elements.forEach(function (element) { cy.add(element) })`) or adding directly to the graph (using `{ (..), "elements": elements, (..) }`). When adding directly to the graph, the core library has no problems with adding the nodes using the 'cose' layout, but when adding dynamically, a warning is shown in the console that nodes probably overlap and therefore edges are impossible to draw. 

I can imagine edges are impossible to draw when at first they overlap, but in the end, the layout determines the position of the nodes and then they don't overlap anymore. Even when using something like `cy.batch(function () {})` to add all nodes (dynamically) at once and then run the layout, the warnings are still shown. 

This does not happen for 'breadthfirst' or 'random' layouts and (as far as I have tested) only for 'bezier' and 'straight' edge styles.

**Desired behaviour**

Some way to suppress these warnings when adding nodes dynamically, while the layout is responsible for the position of nodes.

NOTE: I did find a workaround: a (random) position when adding nodes solves the warning.

**Minimum steps to reproduce**

https://jsbin.com/manukazata/1/edit?js,console,output

### PR DESCRIPTION
**Pull request by Spaxe**
Closes #2258.

Invalidates and closes #2281.

### CODE REVIEW

**Comment by Spaxe** [comment]
Please note that I only ran `npm test` and have not done further investigations to confirm that the option actually works. In theory, it should. Tests are welcome - I'm not as familiar with this code base.

**Comment by maxkfranz** [comment]
This looks great, but now I wonder if we could make it a bit harder to make mistakes with future additions of `warn()` to the code.  Maybe a `cy.warn()` function would be useful.  That way, you can just call `cy.warn()` anywhere in the code without having to check the flag yourself each time.

Or maybe it would be even simpler to just make this a global option under the `cytoscape` object itself rather than per-instance.  E.g. `cytoscape.warnings(false)` would disable warnings on all `cy` instances.  I like this second option a bit better, because the `util.warn()` calls don't have to change at all.  It's also a bit more flexible, since the dev could turn the warnings off and on dynamically.

**Comment by maxkfranz** [comment]
I noticed that some warnings aren't suppressed with this change (e.g. some selector warnings) --- probably because the selector object doesn't have a reference to `cy`.  It might be simpler to use the global approach.

**Comment by Spaxe** [comment]
Correct. I didn't have a way to reference the `cy` object.

Not really a fan to pollute the global scope. Maybe someone else can write a PR and send in a global version. No harm done. :)

**Comment by maxkfranz** [comment]
> Not really a fan to pollute the global scope

To clarify, it's global w.r.t. all `cy` instances -- it's not a global variable under `window`.

**Comment by Spaxe** [comment]
OK, I see in your commit that's how you did it.

It might be easier to cherry pick your commit out of this branch and do another PR - since yours is branched after `util.warn` is called, not before.

**Comment by maxkfranz** [comment]
Merged

**Comment by Spaxe** [comment]
Simplest option is almost always the best. Thanks!

**Pull request closed without merging**
