### PR TITLE
Add support for float numbers (positive & negative) in the z-index style property

### PR DESCRIPTION
**Pull request by maxkfranz**
**Cross-references to related issues.**  If there is no existing issue that describes your bug or feature request, then [create an issue](https://github.com/cytoscape/cytoscape.js/issues/new/choose) before making your pull request.

Associated issues: 
- #3160

**Notes re. the content of the pull request.** Give context to reviewers or serve as a general record of the changes made.  Add a screenshot or video to demonstrate your new feature, if possible.

- Revise `z-index` property to use a `nonNegativeNumber` type rather than `nonNegativeInt`.
- Revise documentation accordingly.
- N.b. this does not change the non-negative constraint on the z-index values.
- This has been manually verified on the debug page.

**Checklist**

Author:

- [x] The proper base branch has been selected.  New features go on `unstable`.  Bug-fix patches can go on either `unstable` or `master`.
- [x] N/A : Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.  Check this box if tests are not pragmatically possible (e.g. rendering features could include screenshots or videos instead of automated tests).
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (above).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.
- [ ] For bug fixes:  Just after this pull request is merged, it should be applied to both the `master` branch and the `unstable` branch.  Normally, this just requires cherry-picking the corresponding merge commit from `master` to `unstable` -- or vice versa.

### CODE REVIEW

**Comment by maxkfranz** [comment]
@d2fong, I've attached a build you can test in Cyweb:

[build.zip](https://github.com/cytoscape/cytoscape.js/files/12742454/build.zip)

**Comment by d2fong** [comment]
thanks I'll test it out.

**Comment by d2fong** [comment]
@maxkfranz Is it possible to also support negative numbers?  Like -1.0, -1.1?

**Comment by maxkfranz** [comment]
> @maxkfranz Is it possible to also support negative numbers? Like -1.0, -1.1?

What's the expected behaviour for a negative number in Cyweb?  

The behaviour of `z-index` in CSS proper is complex for negative values: https://stackoverflow.com/questions/33217407/css-negative-z-index-what-does-it-mean

**Comment by d2fong** [comment]
I would assume that -1.0 would be rendered over -1.1 but let me double check with the cytoscape group.

**Comment by maxkfranz** [comment]
@d2fong, I've removed the restriction on negative numbers in [eff8c8c](https://github.com/cytoscape/cytoscape.js/pull/3171/commits/eff8c8c1b78a15779770a052727dc23c3cacbb23).

Let me know if you run into any issues with it.  Otherwise, let's get this merged for CyWeb.

**Review by d2fong — APPROVED** [review]

**Comment by d2fong** [comment]
Hi Max, its working well.  Thank you.

**Pull request merged**
