### PR TITLE
Fix css class selector.

### PR DESCRIPTION
**Pull request by mkelly1495**
[CSS style selectors with multiple classes are not parsed correctly](https://github.com/cytoscape/cytoscape.js/issues/2995)

### CODE REVIEW

**Comment by maxkfranz** [comment]
@mkelly1495, looks good.

I moved the base branch to `unstable`, because it has GitHub Actions tests.  We've had some trouble with the reliability of Travis and currently only the `unstable` branch has GHA setup.  GHA was just configured recently.

What do you think about moving the `className` beside `variable` and having some sort of comment about the dot?  That would serve two purposes:  (1) It would help to prevent similar errors in future and more strongly show that the two variables are very similar.  (2) It should trigger GHA so we can verify it's working for PRs.

**Comment by mkelly1495** [comment]
Sure - I can do that this weekend.

Michael Kelly

On Mar 18, 2022, at 1:59 PM, Max Franz ***@***.***> wrote:

﻿
@mkelly1495, looks good.

I moved the base branch to unstable, because it has GitHub Actions tests. We've had some trouble with the reliability of Travis and currently only the unstable branch has GHA setup. GHA was just configured recently.

What do you think about moving the className beside variable and having some sort of comment about the dot? That would serve two purposes: (1) It would help to prevent similar errors in future and more strongly show that the two variables are very similar. (2) It should trigger GHA so we can verify it's working for PRs.

**Comment by mkelly1495** [comment]
@maxkfranz I added comments as you requested and moved the definition of `tokens.className` next to the definition of `tokens.variable`. Hopefully it will be clear now why they are different.

**Comment by maxkfranz** [comment]
@mkelly1495 

Sounds good.  I've assigned myself to merge this in and apply it to the applicable branches.  Possibly tomorrow

**Comment by maxkfranz** [comment]
Ref:

- #2999 
- #2995

**Pull request merged**
