### PR TITLE
Fix typo in example code comment (letiation -> variation)

### PR DESCRIPTION
**Pull request by hipe**
I think what probably happened was someone originally wrote "variation" and then there was a search and replace for /^var/ to "let" 😂

### CODE REVIEW

**Comment by maxkfranz** [comment]
You're right.  I think the source md file needs to be updated, though.  The html just comes from a template.  The html is committed so that there's a reference to old versions of the docs by tag.

**Comment by maxkfranz** [comment]
@hipe, are you able to update the source file?

**Comment by hipe** [comment]
indeed! I have added a commit that updates the source file (afaik)

`src/extensions/layout/concentric.js`

As well, this branch commits the resulting change to the several generated files affected by this.

let me know if i can clean up this timeline at all (so it's one commit)! If so, not sure of the best way (a new pull request starting from scratch?) it's such a small change!

Thanks!

**Comment by maxkfranz** [comment]
Looks good.

Don't worry about cleaning up the commits.  The built files should automatically get cleaned up with a fresh build prior to release.  The unstable branch is for collaboration and new ideas, so keeping that branch clean isn't a relatively high priority anyway.

Thanks for the PR

**Pull request merged**
