### PR TITLE
Added 6000 element demo #1392

### PR DESCRIPTION
**Pull request by mj3cheun**

### CODE REVIEW

**Comment by mj3cheun** [comment]
Ok changes made

**Comment by maxkfranz** [comment]
A couple of things:

(1) It would be good to remove the reference to 2.7 on the demo, as it will carry forward to future versions

(2) There needs to be a `fetch()` polyfill for older browsers.  You can just include a ref to a copy from a CDN: https://cdnjs.com/libraries/fetch

**Comment by mj3cheun** [comment]
I have been doing to more testing and I found that fetch doesn't work on Chrome and Chrome derivative browsers when opening the index.html file manually as url scheme "file" is not supported. It works fine when opening the file through a static file server as "http" is being used. It also works fine in firefox. Do you see this as a problem?

**Comment by maxkfranz** [comment]
> I have been doing to more testing and I found that fetch doesn't work on Chrome and Chrome derivative browsers when opening the index.html file manually as url scheme "file" is not supported. It works fine when opening the file through a static file server as "http" is being used. It also works fine in firefox. Do you see this as a problem?

No, it's always running behind an HTTP server.  You should use `http-server` from npm if you want to use the Cyjs debug page or view the docs page etc.

**Comment by mj3cheun** [comment]
Ok made changes and also included promise polyfill just in case.

**Pull request merged**
