### PR TITLE
added a bit code based on commit #825 so that the rotated label text looks bet...

### PR DESCRIPTION
**Pull request by ktei**
@maxkfranz I checked out #825 and it seems the author had implemented almost what I had done and also did much more. So I just changed a bit based on her work to make the text background look better when label text is rotated. Can you have a look?

Cheers

### CODE REVIEW

**Comment by maxkfranz** [comment]
Thanks!  It looks really good.  Do you think it makes sense to centre the labels on edges (as it is with the background) all the time?  Or is there a different usecase that I'm not thinking of?

**Comment by ktei** [comment]
@maxkfranz I think maybe let's just make it easy:
If the 'autorotate' is switched on, then we always center the labels on edges. It is true that however if the user does not declare any background, the labels will be strikethrough be edges, but I think most of the time, people will want background.

**Comment by MissChocoe** [comment]
@ktei That would be the best option. text-border-radius would be the property to addd to do so

**Comment by maxkfranz** [comment]
Maybe a `shape: rectangle | roundrectangle` would be best.  In future, if we allow click events on labels, having a large border radius would complicate the hit tests -- whereas if the `roundrectangle` case has a small, unchangeable border radius then we can assume rectangles for the hit tests.

Thoughts?

**Comment by MissChocoe** [comment]
@maxkfranz totally agree with you, shape property would be enough. 

By the way, I'm working with the unstable version and it seems to go smootly!

**Pull request merged**
