### PR TITLE
Issue-2828: Fixed the issue with retired textures

### PR DESCRIPTION
**Pull request by Alexandr23**
https://github.com/cytoscape/cytoscape.js/issues/2828

### CODE REVIEW

**Comment by maxkfranz** [comment]
@Alexandr23, what do you think about making the PR stronger by changing the `removeFromArray()` function use `true` by default?  That would make it so the optimisation is opt-in rather than opt-out, and it may help with similar issues in future.

**Comment by Alexandr23** [comment]
> Another point to consider is that the remove function seems to start at `array.length`, whereas it should start at `length - 1`. That may be worth addressing at the same time.

Yeah, good catch. I will do this.

**Comment by Alexandr23** [comment]
> @Alexandr23, what do you think about making the PR stronger by changing the `removeFromArray()` function use `true` by default? That would make it so the optimisation is opt-in rather than opt-out, and it may help with similar issues in future.

Yes, I can do this. My only concern is that `removeFromArray` is used in 9 places and I'm only familiar with the caching mechanism. Should we put explicit `false` for the other 6 cases for now?

**Comment by maxkfranz** [comment]
Ultimately, each call to `removeArray()` is going to be O(n) whether it can break early or not.  I think it's fine for all the calls to be more conservative for now, and they can have the flag switched later if there's a large benefit.

**Comment by Alexandr23** [comment]
> Ultimately, each call to `removeArray()` is going to be O(n) whether it can break early or not. I think it's fine for all the calls to be more conservative for now, and they can have the flag switched later if there's a large benefit.

Ok, I updated the PR

**Comment by Alexandr23** [comment]
Hi @maxkfranz, should we improve anything else in this PR?

**Comment by maxkfranz** [comment]
Looks good.  I’ll publish a release later today

**Pull request merged**
