### PR TITLE
FCOSE demo & misc. docs fixes for 3.31.0

### PR DESCRIPTION
**Pull request by maxkfranz**
**Cross-references to related issues.**  If there is no existing issue that describes your bug or feature request, then [create an issue](https://github.com/cytoscape/cytoscape.js/issues/new/choose) before making your pull request.

Associated issues: 

N/A

**Notes re. the content of the pull request.** Give context to reviewers or serve as a general record of the changes made.  Add a screenshot or video to demonstrate your new feature, if possible.

- Add FCOSE gnee-gene demo to replace Cola gene-gene demo
  - While Cola is a good layout, FCOSE is faster and provides better compound support.  It's our default recommendation in the blog (https://blog.js.cytoscape.org/2020/05/11/layouts/).
  - The Cola demo used to be the first one at the top of the demos.  It gives the impression that it's our top/default pick.
  - People end up complaining, "Why can't I do X with Cola?"  If they were to use FCOSE first, they'd get a better result most of the time.
- Miscellaneous fixes to the documentation

**Checklist**

Author:

- [ ] The proper base branch has been selected.  New features go on `unstable`.  Bug-fix patches can go on either `unstable` or `master`.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.  Check this box if tests are not pragmatically possible (e.g. rendering features could include screenshots or videos instead of automated tests).
- [ ] The associated GitHub issues are included (above).
- [ ] Notes have been included (above).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.
- [ ] For bug fixes:  Just after this pull request is merged, it should be applied to both the `master` branch and the `unstable` branch.  Normally, this just requires cherry-picking the corresponding merge commit from `master` to `unstable` -- or vice versa.

### CODE REVIEW

**Comment by maxkfranz** [comment]
@ugurdogrusoz:  Here's a video of the FCOSE demo that replaces the Cola demo (https://js.cytoscape.org/demos/colajs-graph/).  Let us know if you notice anything that should be improved in the new FCOSE demo.  Thanks


https://github.com/user-attachments/assets/765b2f48-c474-4d80-9085-96d16dbce6eb

**Comment by maxkfranz** [comment]
It just iterates the layout a bit, the iterative mode.

If you drag a node out of place it would be more noticeable.

We could remove that button.  I added it because it looked a bit off to only have one.

**Comment by mikekucera** [comment]
Its fine. Maybe just add tooltips to the buttons?

**Comment by ugurdogrusoz** [comment]
The demo looks good but of course, it doesn't illustrate the compound support...

**Comment by maxkfranz** [comment]
> Its fine. Maybe just add tooltips to the buttons?

Tooltips added



> The demo looks good but of course, it doesn't illustrate the compound support...

Since this was meant to replace the Cola slider demo for a non-compound network, I've added a note to the demo with a link to the compound demo.  This just swaps out Cola for FCOSE; I don't have time right now to make it more sophisticated.

Screenshot 2024-12-13 at 13 48 32

We also link to all the FCOSE demos (including compound ones) in the set of demo thumbnails:

Screenshot 2024-12-13 at 13 51 32

**Comment by ugurdogrusoz** [comment]
Great thanks @maxkfranz

**Pull request merged**
