### PR TITLE
Grid layout : condensed & padded

### PR DESCRIPTION
**Pull request by sylvain-hamel**
I have an issue with the grid mode. I use it with `columns : 1, fit: true`. If I only have 2-3 nodes and the canvas is 700px height then I get too much spacing between the nodes and the graph become hard to read. This PR adds a feature to compute the height of the highest cell and then use this value as the *row* height.

What do you think of the idea? 
Should I do the same for columns  (using `autoCellWidth`)?
Do you like the name of the option? Can you think of a better name?

### CODE REVIEW

**Comment by sylvain-hamel** [comment]
I did not add any padding. Maybe `10px` of padding would be better. Would you see the padding as an hardcoded value or do you think an option is necessary for that?

**Comment by maxkfranz** [comment]
There's a later call to `cy.fit( padding )`, so I don't think that's an issue.  A few things, though:

(1) All new features should be PRs on `unstable`.  `master` only gets fixes for minor releases.

(2) Doesn't this work only with one column?

(3) Couldn't you use the existing options, like `boundingBox`, to make the nodes closer together?  A smaller `boundingBox` will put the nodes closer together and zoomed in more.

(4) The layouts all try to use up all the available space.  This depends on screen size and your style.  It may also help to make your nodes etc bigger in your stylesheet.

**Comment by sylvain-hamel** [comment]
Hi,

(1) Sorry about the wrong branch. This is only to get the discussion started. I'll rebase and add the doc if we get to that point.

(2) No. If you have several nodes and one of the node is really high and all the others are short. Then the cell high of all rows and all columns will be equal to the highest.

pic0


(3) `boundingBox` does not prevent overlap :
pic1

(4) In some cases using up all the available space is not optimal. For instance the grid layout produces this:

pic3

But I think that this is more readable:

pic4


----

What do you think or all this? Will you accept this feature if I clean up the PR?

**Comment by sylvain-hamel** [comment]
@maxkfranz I have improved the code a little and I have renamed the option to `autoCellSize` because it now supports both `height` and `width`. Do you plan on accepting this PR. Otherwise we are going to fork the `grid` layout to make our own.
Thanks

**Comment by maxkfranz** [comment]
This PR still isn't on `unstable` so I can't merge.

That aside, I've made a separate commit that doesn't conflict with the previous options and has more modular options.  Please review.

**Comment by sylvain-hamel** [comment]
Hi, I like the result and I like how it extends the current option instead of creating a new option. Next time I'll send PRs on `unstable`. Thanks

**Comment by maxkfranz** [comment]
OK; closing for now

Let me know if anything else comes up regarding this

Thanks!

**Pull request closed without merging**
