### PR TITLE
added loop direction options

### PR DESCRIPTION
**Pull request by tonymullen**
I've added options for having looping edges extend from the node in different directions. The direction is controlled by the 'loop-direction' css selector on edges. Possible options are 'north', 'south', 'east', 'west', 'northeast', 'southeast', 'southwest', and 'northwest' which is the default and is identical to previous looping behavior. 

Addresses issue #783

### CODE REVIEW

**Comment by machow** [comment]
I swapped this branch in for the current version of cytoscape. It threw this error in the browser:

coord-ele-math.js:1331 Uncaught ReferenceError: eStyle is not defined

It's clear eStyle is never defined in that file (but I don't know how cytoscape does globals)

**Comment by maxkfranz** [comment]
@tonymullen This looks great!  I wonder if we should also allow a manual angle value.  That may also help to consolidate the conditionals into a single formula

**Comment by maxkfranz** [comment]
@machow Yes, I don't know about this `eStyle`.  All style values should be read via the internal `ele.pstyle()` (i.e. parsed style) function

**Comment by tonymullen** [comment]
@maxfranz I'll give some thought to how a manual angle should work. 

I guess the control-point step could be made to come into play only when angles were identical. Should there be minimal increments, or would we want to allow arbitrarily closely positioned loops? 

Also, should the loop's internal angle be controllable? Currently north, south, east and west are narrower than the diagonal loops, but this could also be styled.

The direction angle style could allow any value and just calculate the angle by modulo 360. The loop angle would probably need to be constrained to something reasonable (<=90 or so). Maybe just treat any value larger than 90 as 90?

**Comment by maxkfranz** [comment]
I was thinking just to specify the start angle (i.e. angle of the edge as it leaves the node from the beginning / source end).  The loop could just go 90 degrees from there.  I suppose there could be a second property to control the direction: clockwise or counterclockwise.

**Comment by tonymullen** [comment]
Personally, I find 90 degrees to be too broad a sweep for my needs, so I like the idea of being able to set it, or have it default to something smaller, at least for NSEW options.

Setting an angle for the leaving edge seems more confusing to me than setting an angle for the overall direction of the loop (i.e. the angle that bisects the leaving and re-entering edge). So, e.g., 90 degrees would make the loop point straight up (or down, I forget). The loop's leaving and entering angles will always be symmetrical, so this seems like the simplest way to think of loop direction to me. 

I hadn't thought about counterclockwise vs clockwise, but that shouldn't be too difficult to implement. Something like 'loop-sweep-direction' with values 'cw' and 'ccw'.  

So I think I'd propose something like the following four properties: 

'loop-direction' (north, south, etc.)
'loop-direction-angle' (specific angle where 90 corresponds with north, etc. would override 'loop-direction')
'loop-sweep-direction' (cw, ccw)
'loop-sweep-angle' (default 90, min 1, max 135 (arbitrary but sane)).

**Comment by maxkfranz** [comment]
Actually, we'd only need `loop-sweep` and not `-direction` and `-angle`.  The direction can be inferred by the sign.

**Comment by maxkfranz** [comment]
@tonymullen So I think we'd have 

- `loop-direction` : `north`, `south`, or an angle (values like `north` would be converted to their corresponding angles)
- `loop-sweep` : the direction (sign) and amount (angle) the loop sweeps -- can be rad or deg (I think that's already built into the parser)

I think we should have just one default `loop-sweep` value to keep things simple.  Whatever the old loops sweep to should probably be the default so we're backwards compatible.

Thanks for organising this!

**Comment by maxkfranz** [comment]
I really don't know whether `loop-direction` should denote the angle of the source or target parts of the loop.  Maybe it should denote the angle in the middle?  That would make converting values like `north` much more straightforward (e.g. `north` => 12 o'clock).

**Comment by tonymullen** [comment]
Yes, I like the idea of having loop-direction denote the angle in the middle. And getting rid of the compass directions would work fine if that were the case. 

Also, good point about sweep direction being represented by the sign. 

I'll sit down and see about implementing these two properties soon.

**Comment by tonymullen** [comment]
This is coming along fine so far. The only thing I'm unsure of is how to handle the stepping of overlapping edges. It seems to me that loops should step up (increase in size) only if they overlap directly (i.e. have the same direction and sweep angles). The most straightforward way to do this is to check all the loops on the node and step up from the largest one with identical angles. Let me know if you have other ideas on this.

**Comment by tonymullen** [comment]
I think I've resolved the stepping question. This seems to be working as intended.

**Comment by maxkfranz** [comment]
This looks good!  The only thing I think that needs to be revised code wise is the style property types.  They should both be `t.angle`.  That way you can specify `90deg` or `1.57rad`.

Numerical values all get normalised to their preferred units for convenienc, e.g. `ele.pstyle('loop-sweep').pfValue` would be in radians regardless of what units the user specified.

**Comment by tonymullen** [comment]
Still working on getting the deg/rad issues completely sorted out.

**Comment by maxkfranz** [comment]
You should just need to read `.pstyle( someProp ).pfValue` in [lines like this](https://github.com/cytoscape/cytoscape.js/pull/1391/commits/8900fd5ce60732933a79e8fe789bb58b5542e2ca#diff-436f2c18c50462e41ddc306440430eb1R1343) to get the value in radians.  Since you put a default value in the stylesheet, you don't need the `? : ` default value then.

**Comment by tonymullen** [comment]
Sorry, just saw your comment. The code seems to be working now but I'm going to clean it up a bit more with reference to your comment.

**Comment by maxkfranz** [comment]
Great; merged.  Thanks, Tony

**Pull request merged**
